# Generated by Django 6.0.6 on 2026-06-09 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=255)),
                ('business_type', models.CharField(choices=[('GYM', 'Gym'), ('RESTAURANT', 'Restaurant'), ('CAFE', 'Cafe'), ('SALON', 'Salon'), ('AGENCY', 'Agency'), ('PORTFOLIO', 'Portfolio'), ('LAWYER', 'Lawyer'), ('DOCTOR', 'Doctor'), ('REAL_ESTATE', 'Real Estate')], max_length=20)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('primary_color', models.CharField(default='#000000', max_length=7)),
                ('secondary_color', models.CharField(default='#FFFFFF', max_length=7)),
                ('target_audience', models.CharField(blank=True, max_length=255)),
                ('include_testimonials', models.BooleanField(default=True)),
                ('include_pricing', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
