# Generated by Django 6.0.6 on 2026-06-09 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedWebsite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(max_length=255)),
                ('hero_subtitle', models.TextField()),
                ('about_text', models.TextField()),
                ('services', models.JSONField(default=list)),
                ('faq', models.JSONField(blank=True, default=list)),
                ('testimonials', models.JSONField(blank=True, default=list)),
                ('pricing_plans', models.JSONField(blank=True, default=list)),
                ('seo_title', models.CharField(blank=True, max_length=255)),
                ('seo_description', models.TextField(blank=True)),
                ('selected_template', models.CharField(max_length=100)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_websites', to='generator.business')),
            ],
        ),
    ]
