# Generated by Django 6.0.6 on 2026-06-12 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0002_generatedwebsite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generatedwebsite',
            old_name='faq',
            new_name='faqs',
        ),
    ]
